/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type Startup = {
  _id: string;
  _type: "startup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  views?: number;
  description?: string;
  category?: string;
  image?: string;
  pitch?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  name?: string;
  username?: string;
  email?: string;
  image?: string;
  bio?: string;
};

export type Markdown = string;

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | SanityAssetSourceData | Startup | Slug | Author | Markdown;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: STARTUP_QUERY
// Query: *[_type == "startup" && defined(slug.current) && !defined($search) || title match $search || category match $search || author->name match $search] | order(_createdAt desc) {    _id,    title,    image,    slug,    description,    category,    _createdAt,    _type,    _updatedAt,    _rev,    "author": author->{      _id,       name,       image,       bio    },    views  }
export type STARTUP_QUERYResult = Array<{
  _id: string;
  title: null;
  image: string | null;
  slug: null;
  description: null;
  category: null;
  _createdAt: string;
  _type: "author";
  _updatedAt: string;
  _rev: string;
  author: null;
  views: null;
} | {
  _id: string;
  title: string | null;
  image: null;
  slug: null;
  description: string | null;
  category: null;
  _createdAt: string;
  _type: "sanity.fileAsset";
  _updatedAt: string;
  _rev: string;
  author: null;
  views: null;
} | {
  _id: string;
  title: string | null;
  image: null;
  slug: null;
  description: string | null;
  category: null;
  _createdAt: string;
  _type: "sanity.imageAsset";
  _updatedAt: string;
  _rev: string;
  author: null;
  views: null;
} | {
  _id: string;
  title: string | null;
  image: string | null;
  slug: Slug | null;
  description: string | null;
  category: string | null;
  _createdAt: string;
  _type: "startup";
  _updatedAt: string;
  _rev: string;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    bio: string | null;
  } | null;
  views: number | null;
}>;
// Variable: FIND_BY_ID_QUERY
// Query: *[_type == "startup" && _id == $id][0] {    _id,    title,    image,    slug,    description,    category,    _createdAt,    "author": author->{      _id,       name,       image,       bio,username    },    views,    pitch  }
export type FIND_BY_ID_QUERYResult = {
  _id: string;
  title: string | null;
  image: string | null;
  slug: Slug | null;
  description: string | null;
  category: string | null;
  _createdAt: string;
  author: {
    _id: string;
    name: string | null;
    image: string | null;
    bio: string | null;
    username: string | null;
  } | null;
  views: number | null;
  pitch: string | null;
} | null;
// Variable: STARTUP_VIEW_QUERY
// Query: *[_type == "startup" && _id == $id][0] {    _id,    views  }
export type STARTUP_VIEW_QUERYResult = {
  _id: string;
  views: number | null;
} | null;
// Variable: Author_BY_GITHUB_QUERY
// Query: *[_type == "author" && id == $id][0] {    _id,    id,    name,    image,    bio  }
export type Author_BY_GITHUB_QUERYResult = {
  _id: string;
  id: number | null;
  name: string | null;
  image: string | null;
  bio: string | null;
} | null;
// Variable: USER_BY_ID_QUERY
// Query: *[_type == "author" && _id == $id][0] {    _id,    id,    name,    image,    bio  }
export type USER_BY_ID_QUERYResult = {
  _id: string;
  id: number | null;
  name: string | null;
  image: string | null;
  bio: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"startup\" && defined(slug.current) && !defined($search) || title match $search || category match $search || author->name match $search] | order(_createdAt desc) {\n    _id,\n    title,\n    image,\n    slug,\n    description,\n    category,\n    _createdAt,\n    _type,\n    _updatedAt,\n    _rev,\n    \"author\": author->{\n      _id, \n      name, \n      image, \n      bio\n    },\n    views\n  }\n": STARTUP_QUERYResult;
    "\n  *[_type == \"startup\" && _id == $id][0] {\n    _id,\n    title,\n    image,\n    slug,\n    description,\n    category,\n    _createdAt,\n    \"author\": author->{\n      _id, \n      name, \n      image, \n      bio,username\n    },\n    views,\n    pitch\n  }\n": FIND_BY_ID_QUERYResult;
    "\n  *[_type == \"startup\" && _id == $id][0] {\n    _id,\n    views\n  }\n": STARTUP_VIEW_QUERYResult;
    "\n  *[_type == \"author\" && id == $id][0] {\n    _id,\n    id,\n    name,\n    image,\n    bio\n  }\n": Author_BY_GITHUB_QUERYResult;
    "\n  *[_type == \"author\" && _id == $id][0] {\n    _id,\n    id,\n    name,\n    image,\n    bio\n  }\n": USER_BY_ID_QUERYResult;
  }
}
